name: Unit Test

on: push

jobs:
  tests:
    name: unit-test
    runs-on: ubuntu-latest    
    steps:
      - name: checkout base image 
        uses: actions/checkout@v3  
      - uses: addnab/docker-run-action@v3
        with:
          image: buildkite/plugin-tester:v4.0.0
          options: --rm -v ${{ github.workspace }}:/plugin 
          run: bats tests/. 
 
